#9 Stworzenie modelu rejonu
KZC-WAT/local-incident-server pull request #10
Opened 2021-04-06 00:46 UTC by jakub-kowalik

### Stworzono architekturę dla modelu rejonu.

Dodano _spring-boot-starter-data-jpa_ i _h2database_ w _build.gradle_. 
Zostało to dodane w celu testowania, niemniej sugeruje ustalenie spójnej wersji _build.gradle_.

```
REST HTTP POST 'http://localhost:8080/api/region/addRegion' 
przykladowy JSON body:
{
    "regionName": "Warszawa",
    "superRegionName": "Polska"
}
przykladowy JSON response:
{
    "regionId": 2,
    "superRegion": {
        "regionId": 1,
        "superRegion": null,
        "regionName": "Polska"
    },
    "regionName": "Warszawa"
}
201 Created

jeśli superRegion jest podany ale nie istnieje zwracane jest 404
```

```
REST HTTP GET 'http://localhost:8080/api/region/{id}' 
przykladowy JSON response:
{
    "regionId": 1,
    "superRegion": null,
    "regionName": "Polska"
}
200 OK
```
```
REST HTTP GET 'http://localhost:8080/api/region' 
przykladowy JSON response:
[
    {
        "regionId": 1,
        "superRegion": null,
        "regionName": "Polska"
    },
    {
        "regionId": 2,
        "superRegion": {
            "regionId": 1,
            "superRegion": null,
            "regionName": "Polska"
        },
        "regionName": "Warszawa"
    }
]
200 OK
```
```
REST HTTP PUT 'http://localhost:8080/api/region/{id}' 
przykladowy JSON body:
{
    "regionName": "Siedlce",
    "superRegionName": "Polska"
}
przykladowy JSON response:
{
    "regionId": 2,
    "superRegion": {
        "regionId": 1,
        "superRegion": null,
        "regionName": "Polska"
    },
    "regionName": "Siedlce"
}
200 OK
```
```
REST HTTP PATCH 'http://localhost:8080/api/region/{id}' 
przykladowy JSON body:
{
    "regionName": "Pruszków"
}
przykladowy JSON response:
{
    "regionId": 2,
    "superRegion": {
        "regionId": 1,
        "superRegion": null,
        "regionName": "Polska"
    },
    "regionName": "Pruszków"
}
200 OK
```
```
REST HTTP DELETE'http://localhost:8080/api/region/{id}' 
204 No Content
```

2021-04-06 09:34 UTC, Ejden requested changes

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +@RequestMapping("/api/region")
Przydałoby się wersjonowanie api. Czyli powinno być 
```suggestion
@RequestMapping("api/v1/region")
```

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    @GetMapping()
```suggestion
    @GetMapping
```

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    @GetMapping("/{regionId}")
```suggestion
    @GetMapping("{regionId}")
```

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    @GetMapping("/{regionId}")
Nie trzeba dodawać tych / na początku :) Spring sam je dodaje

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    public ResponseEntity<RegionEntity> getRegion(@PathVariable Long regionId) {
Zastanawiam się czy nie lepiej pracować na UUID? Do dyskusji będzie

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    @PostMapping("/addRegion")
```suggestion
    @PostMapping("addRegion")
```

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +            return new ResponseEntity<>(regionService.saveRegion(regionRequest), HttpStatus.CREATED);
```suggestion
            RegionEntity region = regionService.saveRegion(regionRequest);
            URI location = ServletUriComponentsBuilder
                         .fromCurrentRequest()
                         .path("/{id}")
                         .buildAndExpand(region.getId())
                         .toUri();
            return ResponseEntity.created(location).body(region).build();
```
Coś w tym stylu powinno być. Przy POST niech zwraca też lokalizację tego obiektu.

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    @PutMapping("/{regionId}")
```suggestion
    @PutMapping("{regionId}")
```

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    @PutMapping("/{regionId}")
Generalnie można pousuwać wszędzie te / na początku

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +@Builder
Hmm, ten Builder chyba niepotrzebny jak są tylko 3 pola mi się wydaje

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +    private RegionRepository regionRepository;
```suggestion
    private final RegionRepository regionRepository;
```

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionRepository.java
> +public interface RegionRepository extends CrudRepository<RegionEntity, Long> {
```suggestion
public interface RegionRepository extends JpaRepository<RegionEntity, Long> {
```
Jeśli dobrze pamietam to CrudRepository nie ma możliwości stronicowania

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +    public Iterable<RegionEntity> getAllRegions() {
Tutaj trzeba to będzie zrobić ze stronicowaniem. Trzeba wykorzystać klasę Pageable.

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +        if (dto.getRegionName() != null)
Tutaj trzeba raczej skorzystać z innego podejścia zamiast sprawdzania nulli. Skorzystałbym z JsonNullable. Więcej tutaj: https://medium.com/techno101/partial-updates-patch-in-spring-boot-63ff35582250

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +        if (dto.getRegionName() != null)
A dlaczego? No bo jak załóżmy ktoś by chciał zrobić jakieś pole na null no to tutaj stwierdzi, że nie chce go zmieniać skoro podałes nulla

2021-04-06 09:34 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/request/RegionRequest.java
> +@Builder
Niepotrzebny Builder

2021-04-06 14:28 UTC, KrizzyK commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +@Builder
Nie powinno się robić tak, że raz builderem, raz nie . Powinnismy, niezależnie od ilości atrybutów, trzymać się jednego schematu w całym projekcie, żeby kod był bardziej czytelny. Więc moim zdaniem albo wszystko builderem, albo nic

2021-04-06 14:43 UTC, kszapsza reviewed
Chyba nazwy się złe wkradły w metodach kontrolera ;p

2021-04-06 14:43 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    public ResponseEntity<RegionEntity> replaceEmployee(@PathVariable Long regionId, @RequestBody RegionRequest regionRequest) {
```suggestion
    public ResponseEntity<RegionEntity> replaceRegion(@PathVariable Long regionId, @RequestBody RegionRequest regionRequest) {
```

2021-04-06 14:43 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    public ResponseEntity<RegionEntity> modifyEmployee(@PathVariable Long regionId, @RequestBody RegionRequest regionRequest) {
```suggestion
    public ResponseEntity<RegionEntity> modifyRegion(@PathVariable Long regionId, @RequestBody RegionRequest regionRequest) {
```

2021-04-06 14:54 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +@Builder
@Ejden na następnym spotkaniu powinniśmy omówić takie rzeczy, w tym spójny styl kodowania dla całego projektu.

2021-04-06 18:31 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +    public Iterable<RegionEntity> getAllRegions() {
Rozwiązano w 019abc1a1222dd732c74034a997959f8e45f3233

2021-04-06 18:42 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +    @PostMapping("addRegion")
```suggestion
    @PostMapping
```

W restowym API nie powinniśmy nazywać endpointów z wykorzystaniem nazw z czasownikami, wystarczający jest czasownik HTTP POST i nazwa endpointa `/api/v1/region`.

Ponadto dodawany w nagłówku HTTP `Location` adres nowego zasobu jest tworzony z kontekstu requestu (`.fromCurrentRequest()`). Ponieważ ten endpoint ma dodane owe `addRegion`, to Location pojawia się niewłaściwie, np. `/api/v1/region/addRegion/1` zamiast `/api/v1/region/1`.

2021-04-06 18:59 UTC, kszapsza commented
Jeszcze taka jedna rzecz, czy wyjątki unchecked (rozszerzające `RuntimeException`) też chcemy zapisywać w nagłówkach metod?Takie wyjątki mogą paść w wielu miejscach i może się szybko zrobić spory zamęt w kodzie (kompilator wymaga jedynie podawania w metodach `throws` z nazwą wyjątku dla wyjątków checked, które muszą być obsłużone)

2021-04-06 19:07 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +    public RegionEntity DTOtoEntity(RegionRequest regionRequest) throws RegionNotFoundException {
Piszę jeszcze raz tutaj bo nie dało się komentować wpisu na głównej tablicy PR 😁

Jeszcze taka jedna rzecz, czy wyjątki unchecked (rozszerzające RuntimeException) też chcemy zapisywać w nagłówkach metod? Takie wyjątki mogą paść w wielu miejscach i może się szybko zrobić spory zamęt w kodzie (kompilator wymaga jedynie podawania w metodach throws z nazwą wyjątku dla wyjątków checked, które muszą być obsłużone).

2021-04-06 19:49 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +    public RegionEntity DTOtoEntity(RegionRequest regionRequest) throws RegionNotFoundException {
@kszapsza nie było ustalonego stylu kodowania dlatego starałem się robić tak jak w projekcie wrzuconym na discordzie.

2021-04-06 19:53 UTC, kszapsza approved these changes

2021-04-07 16:54 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +        if (dto.getRegionName() != null)
Rozwiazano w 1a85b941fc85628cecde3457b90014cffd33fcd7

2021-04-07 16:59 UTC, jakub-kowalik commented
Przykładowe zapytania po zmianach:
```
REST HTTP GET 'http://localhost:8080/api/v1/region' 
przykladowy JSON response:
{
    "content": [
        {
            "regionId": 1,
            "superRegion": null,
            "regionName": "Polska"
        },
        {
            "regionId": 2,
            "superRegion": {
                "regionId": 1,
                "superRegion": null,
                "regionName": "Polska"
            },
            "regionName": "Warszawa"
        },
        {
            "regionId": 3,
            "superRegion": {
                "regionId": 1,
                "superRegion": null,
                "regionName": "Polska"
            },
            "regionName": "Katowice"
        },
        {
            "regionId": 4,
            "superRegion": {
                "regionId": 1,
                "superRegion": null,
                "regionName": "Polska"
            },
            "regionName": "Gdansk"
        },
        {
            "regionId": 5,
            "superRegion": {
                "regionId": 2,
                "superRegion": {
                    "regionId": 1,
                    "superRegion": null,
                    "regionName": "Polska"
                },
                "regionName": "Warszawa"
            },
            "regionName": "Bemowo"
        }
    ],
    "pageable": {
        "sort": {
            "sorted": true,
            "unsorted": false,
            "empty": false
        },
        "offset": 0,
        "pageNumber": 0,
        "pageSize": 5,
        "paged": true,
        "unpaged": false
    },
    "last": false,
    "totalElements": 7,
    "totalPages": 2,
    "size": 5,
    "number": 0,
    "sort": {
        "sorted": true,
        "unsorted": false,
        "empty": false
    },
    "first": true,
    "numberOfElements": 5,
    "empty": false
}
200 OK
```
```
REST HTTP PATCH 'http://localhost:8080/api/region/{id}' 
przykladowy JSON body:
{
    "superRegionName": null
}
przykladowy JSON response:
{
    "regionId": 2,
    "superRegion": null,
    "regionName": "Warszawa"
}
200 OK
```

2021-04-07 17:18 UTC, Ejden commented
Rozwiąż konflikt. Zaakcpeptuj tylko wersję z test. Swoją możesz odrzucić z pliku build.gradle bo już jest zmergowana moja wersja z bazą danych. Jak będziesz miał wątpliwości jak to zrobisz to napisz na dc

2021-04-07 17:54 UTC, Ejden requested changes

2021-04-07 17:54 UTC, Ejden commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
To będzie można wyrzucić. Na repo jest już wersja z postgresem. Czyli zrobić to co pisałem w wiadomościach do pr

2021-04-07 17:54 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +    private String regionName;
regionName może być pustym stringiem. Dodaj jeszcze minimalną długość na 3 znaki. Patrz: Adnotacja @Size z javax.validation.constraints

2021-04-07 17:54 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +        if (dto.getSuperRegionName() != null && dto.getSuperRegionName().equals(regionEntity.getRegionName()))
Czemu służy ta linijka? Bo jakoś ciężko zrozumieć mi jej istnienie :P

2021-04-07 17:54 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +            if (dto.getRegionName().get() != null)
Tutaj niepotrzebne jest te sprawdzenie czy nie jest nullem. Wywali się i tak przy próbie zapisu do bazy danych skoro kolumna nie jest nullable

2021-04-07 17:54 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +            if (dto.getSuperRegionName().get() != null && !dto.getSuperRegionName().get().equals(regionEntity.getRegionName()))
Zamiast przydzielać po nazwie super rejonu lepiej jest tutaj dac id super rejonu

2021-04-07 17:54 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +        regionRepository.findAllBySuperRegion(superRegion)
To jest niepotrzebne. Sprawdź sobie adnotacje dotyczące usuwania typu SET NULL, CASCADE itd

2021-04-07 21:44 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +    private String regionName;
Wystarczy nazwa `name`, `regionName` jest nadmiarowe – „region” wynika z kontekstu – nazwy klasy.
A sama klasa mogłaby się w sumie nazywać po prostu `Region`, ale to można jeszcze przedyskutować

2021-04-07 22:00 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +        if (dto.getSuperRegionName() != null && dto.getSuperRegionName().equals(regionEntity.getRegionName()))
Wydaje mi się, że chyba miało tu być zanegowane, `!dto.getSuperRegionName().equals(regionEntity.getRegionName()`, tzn. region nie może być swoim własnym rodzicem. Tu też podobnie jak Adrian myślę, że lepiej byłoby w requeście przekazywać ID regionu-rodzica, zamiast jego nazwy. ID zawsze będzie unikalne.

2021-04-08 09:04 UTC, Ejden commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +    private String regionName;
Zgadzam się. Nie zwróciłem nawet uwagi na to

2021-04-08 21:43 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +    private String regionName;
Rozwiązano w d1fae926ab6d8b8978eb360a4f8986697d2e01e6

2021-04-08 21:45 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionEntity.java
> +    private String regionName;
Rozwiązano w d1fae926ab6d8b8978eb360a4f8986697d2e01e6

2021-04-09 11:12 UTC, Ejden commented
Zmień jedynie nazwę tego RegionEntity na Region i będzie ok

2021-04-09 11:58 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/request/RegionRequest.java
> +    private String regionName;
Tu znów się naciąłem jak testowałem teraz w Postmanie😉 wystarczy name, `region` wynika z kontekstu

```suggestion
    private String name;
```

2021-04-09 12:00 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +    public RegionRequest EntityToDTO(RegionEntity regionEntity) {
```suggestion
    public RegionRequest entityToDto(RegionEntity regionEntity) {
```

camelCase

2021-04-09 12:01 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +    public RegionEntity DTOtoEntity(RegionRequest regionRequest) throws RegionNotFoundException {
```suggestion
    public RegionEntity dtoToEntity(RegionRequest regionRequest) throws RegionNotFoundException {
```

camelCase

2021-04-09 12:02 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +public class RegionFactory {
```suggestion
public class RegionMapper {
```

Fabryka to bardziej przy wzorcu fabryki, tutaj może lepiej nazwać `RegionMapper`, mapuje dto<->entity?

2021-04-09 12:07 UTC, kszapsza commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +@RequestMapping("api/v1/region")
```suggestion
@RequestMapping("api/v1/regions")
```

2021-04-09 20:19 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionController.java
> +@RequestMapping("api/v1/region")
Rozwiązano w 55cfd9c29baf1facb022469b315842b71d6b0af3

2021-04-09 20:19 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +    public RegionEntity DTOtoEntity(RegionRequest regionRequest) throws RegionNotFoundException {
Rozwiązano w 55cfd9c29baf1facb022469b315842b71d6b0af3

2021-04-09 20:19 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionFactory.java
> +    public RegionRequest EntityToDTO(RegionEntity regionEntity) {
Rozwiązano w 55cfd9c29baf1facb022469b315842b71d6b0af3

2021-04-09 20:20 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/request/RegionRequest.java
> +    private String regionName;
Rozwiązano w 55cfd9c29baf1facb022469b315842b71d6b0af3

2021-04-09 20:20 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +            if (dto.getRegionName().get() != null)
Rozwiązano w 55cfd9c29baf1facb022469b315842b71d6b0af3

2021-04-09 20:22 UTC, jakub-kowalik commented on src/main/java/pl/kzcwat/localincidentserver/region/RegionService.java
> +        if (dto.getSuperRegionName() != null && dto.getSuperRegionName().equals(regionEntity.getRegionName()))
Rozwiązano w 55cfd9c29baf1facb022469b315842b71d6b0af3

2021-04-09 20:26 UTC, jakub-kowalik commented
```
REST HTTP PATCH 'http://localhost:8080/api/v1/regions/{id}' 
przykładowy JSON body przy podaniu nieprawidłowego nadregionu (self-reference):
{
    "superRegionId": 1
}
przykladowy response:
400 Bad Request
```
```
REST HTTP PUT 'http://localhost:8080/api/regions/{id}' 
przykładowy JSON body przy podaniu nieprawidłowego nadregionu (self-reference):
{
    "name": "Polska",
    "superRegionId": 1
}
przykladowy response:
400 Bad Request
```

2021-04-10 08:43 UTC, Ejden approved these changes

2021-04-10 12:51 UTC, kszapsza approved these changes

2021-04-10 13:34 UTC, merged